'use client';
import '@/styles/globals.css';
import { useRouter } from 'next/router';
import Navbar from './navbar';
import { ChakraProvider } from '@chakra-ui/react';
import type { AppProps } from 'next/app';
import Footer from './footer';
import Nav2 from './navbar2';
import Head from 'next/head';
import { Analytics } from '@vercel/analytics/react';
function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  if (router.pathname === '/signup' || router.pathname === '/signin') {
    // Render the component without the navbar

    return (
      <ChakraProvider>
        <Nav2 />
        <Component {...pageProps} />
      </ChakraProvider>
    );
  }
  return (
    <>
      <Head>
        <title>EvenX | Next-generation finance powered by technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/newlogo.png" />
      </Head>
      <ChakraProvider>
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </ChakraProvider>
      <Analytics />
    </>
  );
}

export default MyApp;
